Improve build errors reporting

diff --git a/scripts/valhalla_build_timezones b/scripts/valhalla_build_timezones
--- a/scripts/valhalla_build_timezones
+++ b/scripts/valhalla_build_timezones
@@ -1,18 +1,16 @@
 #!/bin/sh
 
 error_exit() {
-  echo "$1" 1>&2
-  #exit 1
+  echo "error: $1" 1>&2
+  exit 1
 }
 
 if  ! which spatialite >/dev/null; then
-    echo "spatialite not found which is required.  Please install via:  sudo apt-get install spatialite-bin"
-    exit 1
+    error_exit "spatialite not found which is required.  Please install via:  sudo apt-get install spatialite-bin"
 fi
 
 if  ! which unzip >/dev/null; then
-    echo "unzip not found which is required.  Please install via:  sudo apt-get install unzip"
-    exit 1
+    error_exit "unzip not found which is required.  Please install via:  sudo apt-get install unzip"
 fi
 
 rm -rf dist
@@ -227,13 +225,13 @@ Africa/Timbuktu,Africa/Abidjan
 Atlantic/St_Helena,Africa/Abidjan
 EOF
 
-echo "downloading timezone polygon file." 1>&2 
+echo "downloading timezone polygon file." 1>&2
 curl -L -s -o ./timezones-with-oceans.shapefile.zip ${url} || error_exit "wget failed for " ${url}
 unzip ./timezones-with-oceans.shapefile.zip 1>&2 || error_exit "unzip failed"
 
 tz_file=$(mktemp)
 spatialite_tool -i -shp ./dist/combined-shapefile-with-oceans -d ${tz_file} -t tz_world -s 4326 -g geom -c UTF-8 1>&2 || error_exit "spatialite_tool import failed"
-spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" 1>&2 || error_exit "SpatialIndex failed" 
+spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" 1>&2 || error_exit "SpatialIndex failed"
 
 spatialite ${tz_file} "DROP TABLE IF EXISTS "alias";" 1>&2 || error_exit "drop table alias failed"
 spatialite ${tz_file} "CREATE TABLE "alias" (alias_TZID text,alias_new_TZID text);" 1>&2 || error_exit "create table alias failed"
