Init

diff --git a/scripts/valhalla_build_timezones b/scripts/valhalla_build_timezones
--- a/scripts/valhalla_build_timezones
+++ b/scripts/valhalla_build_timezones
@@ -1,20 +1,28 @@
 #!/bin/sh
 
-if  ! which spatialite >/dev/null; then
-  echo "Error: spatialite not found which is required. Please install via: apt-get install spatialite-bin"
+error_exit() {
+  echo "error: $1" 1>&2
+  # geos 3.9* has a double free bug which, although it crashes the programs
+  # that use it when they go to exit, works fine otherwise in terms of the
+  # output. so here if we detect that we ignore the failure and keep going
+  if [ $(pkg-config geos --modversion | grep -cvF "3.9") -eq 0 ]; then
+    exit 1
+  fi
+}
+
+if  ! which spatialite > /dev/null; then
+  error_exit "spatialite not found which is required. Please install spatialite-bin"
 fi
 
-if  ! which unzip >/dev/null; then
-  echo "Error: unzip not found which is required. Please install via: apt-get install unzip"
+if  ! which unzip > /dev/null; then
+  error_exit "unzip not found which is required. Please install unzip"
 fi
-
-unzip /data/timezones-with-oceans.shapefile.zip
 
 tz_file=$(mktemp)
-spatialite_tool -i -shp "./combined-shapefile-with-oceans" -d "${tz_file}" -t tz_world -s 4326 -g geom -c UTF-8
-spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');"
-spatialite ${tz_file} "VACUUM;"
-spatialite ${tz_file} "ANALYZE;"
+spatialite_tool -i -shp "./combined-shapefile-with-oceans" -d "${tz_file}" -t tz_world -s 4326 -g geom -c UTF-8 1>&2 || error_exit "spatialite_tool import failed"
+spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" 1>&2 || error_exit "SpatialIndex failed"
+spatialite ${tz_file} "VACUUM;" 1>&2 || error_exit "VACUUM failed"
+spatialite ${tz_file} "ANALYZE;" 1>&2 || error_exit "ANALYZE failed"
 
 rm -rf /data/combined-shapefile-with-oceans* /data/alias_tz.csv
 
