Update valhalla_build_timezones

diff --git a/scripts/valhalla_build_timezones b/scripts/valhalla_build_timezones
--- a/scripts/valhalla_build_timezones
+++ b/scripts/valhalla_build_timezones
@@ -2,13 +2,13 @@
 
 set -e  # Exit immediately if a command exits with a non-zero status
 
-if [ "$param" = "-d" ]; then
-  echo 'Downloading timezone polygon file "timezones-with-oceans.shapefile.zip"...'
+if [ $1 = "-d" ]; then
+  echo 'Downloading timezone polygon file "timezones-with-oceans.shapefile.zip"...' 1>&2
 
-  wget https://github.com/evansiroky/timezone-boundary-builder/releases/download/2024a/timezones-with-oceans.shapefile.zip || exit 1
+  wget https://github.com/evansiroky/timezone-boundary-builder/releases/download/2024a/timezones-with-oceans.shapefile.zip 1>&2  || exit 1
 else
   if [ ! -f ./timezones-with-oceans.shapefile.zip ]; then
-    echo 'Timezone polygon file "timezones-with-oceans.shapefile.zip" is not found'
+    echo 'Timezone polygon file "timezones-with-oceans.shapefile.zip" is not found' 1>&2
   
     exit 1
   fi
@@ -16,15 +16,15 @@ fi
 
 echo 'Unzip timezone polygon file "timezones-with-oceans.shapefile.zip"...'
 
-unzip ./timezones-with-oceans.shapefile.zip || exit 1
+unzip ./timezones-with-oceans.shapefile.zip 1>&2 || exit 1
 
-echo "Create spatial database..."
+echo "Create spatial database..." 1>&2
 
 tz_file=$(mktemp)
-spatialite_tool -i -shp ./combined-shapefile-with-oceans -d ${tz_file} -t tz_world -s 4326 -g geom -c UTF-8 || exit 1
-spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" || exit 1
-spatialite ${tz_file} "VACUUM;" || exit 1
-spatialite ${tz_file} "ANALYZE;" || exit 1
+spatialite_tool -i -shp ./combined-shapefile-with-oceans -d ${tz_file} -t tz_world -s 4326 -g geom -c UTF-8 1>&2 || exit 1
+spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" 1>&2 || exit 1
+spatialite ${tz_file} "VACUUM;" 1>&2 || exit 1
+spatialite ${tz_file} "ANALYZE;" 1>&2 || exit 1
 
 rm -rf /data/combined-shapefile-with-oceans* /data/alias_tz.csv
 
