properly build timezones on geos 3.9*

diff --git a/scripts/valhalla_build_timezones b/scripts/valhalla_build_timezones
--- a/scripts/valhalla_build_timezones
+++ b/scripts/valhalla_build_timezones
@@ -2,7 +2,12 @@
 
 error_exit() {
   echo "error: $1" 1>&2
-  #exit $(pkg-config geos --modversion | grep -cvF "3.9")
+  # geos 3.9* has a double free bug which, although it crashes the programs
+  # that use it when they go to exit, works fine otherwise in terms of the
+  # output. so here if we detect that we ignore the failure and keep going
+  if [ $(pkg-config geos --modversion | grep -cvF "3.9") -eq 0 ]; then
+    exit 1
+  fi
 }
 
 if  ! which spatialite >/dev/null; then
