for some reason the cache entries are 'directories'

diff --git a/.github/workflows/clean_cache.yml b/.github/workflows/clean_cache.yml
--- a/.github/workflows/clean_cache.yml
+++ b/.github/workflows/clean_cache.yml
@@ -29,5 +29,5 @@ jobs:
           done
 
           for entry in $filtered; do
-            mc rm hetzner/gha-cache/${entry} || echo "couldn't find $entry"
+            mc rm --recursive --force hetzner/gha-cache/${entry} || echo "couldn't find $entry"
           done
