need to re-install the git hook

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -64,236 +64,236 @@ jobs:
           env DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes --quiet sudo python3-pip python3-requests git curl file
           ./scripts/format.sh && ./scripts/error_on_dirty.sh
 
-  # release_build:
-  #   name: Release build
-  #   runs-on: ubuntu-22.04
-  #   needs: [lint_format]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #         fetch-depth: 1
+  release_build:
+    name: Release build
+    runs-on: ubuntu-22.04
+    needs: [lint_format]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          fetch-depth: 1
 
-  #     - uses: actions/setup-python@v6
-  #       with:
-  #         python-version: '3.12'
+      - uses: actions/setup-python@v6
+        with:
+          python-version: '3.12'
       
-  #     - name: Install deps
-  #       run: |
-  #         ./scripts/install-linux-deps.sh
-  #         python -m pip install requests shapely
+      - name: Install deps
+        run: |
+          ./scripts/install-linux-deps.sh
+          python -m pip install requests shapely
       
-  #     - name: Get timestamp & ccache dir
-  #       run: |
-  #         echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
-  #         echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
+      - name: Get timestamp & ccache dir
+        run: |
+          echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
+          echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
 
-  #     - name: Restore ccache
-  #       uses: tespkg/actions-cache/restore@v1
-  #       id: cache-ccache-restore
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-release-linux-x86_64-${{ env.BRANCH_NAME }}
-  #         restore-keys: |
-  #           ccache-release-linux-x86_64-master
-  #           ccache-release-linux-x86_64
+      - name: Restore ccache
+        uses: tespkg/actions-cache/restore@v1
+        id: cache-ccache-restore
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-release-linux-x86_64-${{ env.BRANCH_NAME }}
+          restore-keys: |
+            ccache-release-linux-x86_64-master
+            ccache-release-linux-x86_64
       
-  #     - name: Build Valhalla
-  #       run: |
-  #         # NOTE: -Werror disabled in CI, as we currently have >4k warnings.
-  #         cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On -DLOGGING_LEVEL=TRACE \
-  #           -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_SUFFIX="-0ubuntu1-$(lsb_release -sc)" -DENABLE_SANITIZERS=ON \
-  #           -DENABLE_SINGLE_FILES_WERROR=Off -DENABLE_GDAL=On
-  #         make -C build -j$(nproc)
-  #         make -C build -j$(nproc) utrecht_tiles
-  #         make -C build -j$(nproc) tests gurka
+      - name: Build Valhalla
+        run: |
+          # NOTE: -Werror disabled in CI, as we currently have >4k warnings.
+          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On -DLOGGING_LEVEL=TRACE \
+            -DCPACK_GENERATOR=DEB -DCPACK_PACKAGE_VERSION_SUFFIX="-0ubuntu1-$(lsb_release -sc)" -DENABLE_SANITIZERS=ON \
+            -DENABLE_SINGLE_FILES_WERROR=Off -DENABLE_GDAL=On
+          make -C build -j$(nproc)
+          make -C build -j$(nproc) utrecht_tiles
+          make -C build -j$(nproc) tests gurka
 
-  #     - name: Save ccache
-  #       if: always()
-  #       uses: tespkg/actions-cache/save@v1
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-release-linux-x86_64-${{ env.BRANCH_NAME }}
+      - name: Save ccache
+        if: always()
+        uses: tespkg/actions-cache/save@v1
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-release-linux-x86_64-${{ env.BRANCH_NAME }}
 
-  #     - name: Run tests
-  #       run: |
-  #         ASAN_OPTIONS="detect_leaks=0" make -C build -j$(nproc) check
-  #         # remove the huge trace logs
-  #         rm -f build/test/*.log
+      - name: Run tests
+        run: |
+          ASAN_OPTIONS="detect_leaks=0" make -C build -j$(nproc) check
+          # remove the huge trace logs
+          rm -f build/test/*.log
       
-  #     - name: Install Valhalla
-  #       run: |
-  #         sudo make -C build install
-  #         make -C build package
+      - name: Install Valhalla
+        run: |
+          sudo make -C build install
+          make -C build package
       
-  #     - name: Setup tmate session
-  #       uses: mxschmitt/action-tmate@v3
-  #       if: ${{ env.SETUP_TMATE == 'true' || failure() }}
-  #       with:
-  #         detached: true
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
+        with:
+          detached: true
 
-  # debug_build:
-  #   name: Debug build
-  #   runs-on: ubuntu-latest
-  #   needs: [lint_format]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #         fetch-depth: 1
+  debug_build:
+    name: Debug build
+    runs-on: ubuntu-latest
+    needs: [lint_format]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          fetch-depth: 1
 
-  #     - uses: actions/setup-python@v6
-  #       with:
-  #         python-version: '3.12'
+      - uses: actions/setup-python@v6
+        with:
+          python-version: '3.12'
       
-  #     - name: Install deps
-  #       run: |
-  #         ./scripts/install-linux-deps.sh
-  #         python -m pip install requests shapely
+      - name: Install deps
+        run: |
+          ./scripts/install-linux-deps.sh
+          python -m pip install requests shapely
 
-  #     - name: Get timestamp & ccache dir
-  #       run: |
-  #         echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
-  #         echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
+      - name: Get timestamp & ccache dir
+        run: |
+          echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
+          echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
 
-  #     - name: Restore ccache
-  #       uses: tespkg/actions-cache/restore@v1
-  #       id: cache-ccache-restore
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-debug-linux-x86_64-${{ env.BRANCH_NAME }}
-  #         restore-keys: |
-  #           ccache-debug-linux-x86_64-master
-  #           ccache-debug-linux-x86_64
+      - name: Restore ccache
+        uses: tespkg/actions-cache/restore@v1
+        id: cache-ccache-restore
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-debug-linux-x86_64-${{ env.BRANCH_NAME }}
+          restore-keys: |
+            ccache-debug-linux-x86_64-master
+            ccache-debug-linux-x86_64
       
-  #     - name: Build Valhalla
-  #       run: |
-  #         # NOTE: -Werror disabled in CI, as we currently have >4k warnings.
-  #         cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DCPACK_GENERATOR=DEB \
-  #           -DENABLE_COMPILER_WARNINGS=On -DENABLE_WERROR=Off -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
-  #           -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DLOGGING_LEVEL=INFO -DENABLE_PYTHON_BINDINGS=On -DENABLE_GDAL=On \
-  #           -DBUILD_SHARED_LIBS=On
-  #         make -C build -j$(nproc)
-  #         make -C build -j$(nproc) utrecht_tiles
-  #         make -C build -j$(nproc) tests gurka
+      - name: Build Valhalla
+        run: |
+          # NOTE: -Werror disabled in CI, as we currently have >4k warnings.
+          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DCPACK_GENERATOR=DEB \
+            -DENABLE_COMPILER_WARNINGS=On -DENABLE_WERROR=Off -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
+            -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DLOGGING_LEVEL=INFO -DENABLE_PYTHON_BINDINGS=On -DENABLE_GDAL=On \
+            -DBUILD_SHARED_LIBS=On
+          make -C build -j$(nproc)
+          make -C build -j$(nproc) utrecht_tiles
+          make -C build -j$(nproc) tests gurka
 
-  #     - name: Save ccache
-  #       if: always()
-  #       uses: tespkg/actions-cache/save@v1
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-debug-linux-x86_64-${{ env.BRANCH_NAME }}
+      - name: Save ccache
+        if: always()
+        uses: tespkg/actions-cache/save@v1
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-debug-linux-x86_64-${{ env.BRANCH_NAME }}
       
-  #     - name: Run clang-tidy
-  #       run: scripts/clang-tidy-only-diff.sh $(nproc)
+      - name: Run clang-tidy
+        run: scripts/clang-tidy-only-diff.sh $(nproc)
 
-  #     - name: Run tests
-  #       run: make -C build -j$(nproc) check
+      - name: Run tests
+        run: make -C build -j$(nproc) check
       
-  #     - name: Install & Package Valhalla
-  #       run: |
-  #         df -h
-  #         sudo make -C build install
-  #         make -C build package
+      - name: Install & Package Valhalla
+        run: |
+          df -h
+          sudo make -C build install
+          make -C build package
 
-  #     - uses: codecov/codecov-action@v5
-  #       name: Upload codecov report
-  #       with:
-  #         fail_ci_if_error: true
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         verbose: true
+      - uses: codecov/codecov-action@v5
+        name: Upload codecov report
+        with:
+          fail_ci_if_error: true
+          token: ${{ secrets.CODECOV_TOKEN }}
+          verbose: true
       
-  #     - name: Setup tmate session
-  #       uses: mxschmitt/action-tmate@v3
-  #       if: ${{ env.SETUP_TMATE == 'true' || failure() }}
-  #       with:
-  #         detached: true
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
+        with:
+          detached: true
 
-  # arm_build:
-  #   name: ARM build
-  #   runs-on: ubuntu-22.04-arm
-  #   needs: [lint_format]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #         fetch-depth: 1
+  arm_build:
+    name: ARM build
+    runs-on: ubuntu-22.04-arm
+    needs: [lint_format]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          fetch-depth: 1
 
-  #     - uses: actions/setup-python@v6
-  #       with:
-  #         python-version: '3.12' 
+      - uses: actions/setup-python@v6
+        with:
+          python-version: '3.12' 
       
-  #     - name: Install deps
-  #       run: |
-  #         ./scripts/install-linux-deps.sh
-  #         python -m pip install requests shapely
+      - name: Install deps
+        run: |
+          ./scripts/install-linux-deps.sh
+          python -m pip install requests shapely
 
-  #     - name: Get timestamp & ccache dir
-  #       run: |
-  #         echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
-  #         echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
+      - name: Get timestamp & ccache dir
+        run: |
+          echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_ENV
+          echo "CCACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV
 
-  #     - name: Restore ccache
-  #       uses: tespkg/actions-cache/restore@v1
-  #       id: cache-ccache-restore
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-release-linux-aarch64-${{ env.BRANCH_NAME }}
-  #         restore-keys: |
-  #           ccache-release-linux-aarch64-master
-  #           ccache-release-linux-aarch64
+      - name: Restore ccache
+        uses: tespkg/actions-cache/restore@v1
+        id: cache-ccache-restore
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-release-linux-aarch64-${{ env.BRANCH_NAME }}
+          restore-keys: |
+            ccache-release-linux-aarch64-master
+            ccache-release-linux-aarch64
       
-  #     - name: Build Valhalla
-  #       run: |
-  #         cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On \
-  #           -DENABLE_SINGLE_FILES_WERROR=Off -DENABLE_GDAL=On
-  #         make -C build -j$(nproc)
-  #         # make -C build -j$(nproc) utrecht_tiles
-  #         make -C build -j$(nproc) gurka
+      - name: Build Valhalla
+        run: |
+          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On \
+            -DENABLE_SINGLE_FILES_WERROR=Off -DENABLE_GDAL=On
+          make -C build -j$(nproc)
+          # make -C build -j$(nproc) utrecht_tiles
+          make -C build -j$(nproc) gurka
 
-  #     - name: Save ccache
-  #       if: always()
-  #       uses: tespkg/actions-cache/save@v1
-  #       with:
-  #         endpoint: hel1.your-objectstorage.com
-  #         accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
-  #         secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
-  #         bucket: gha-cache
-  #         path: /home/runner/.cache/ccache
-  #         key: ccache-release-linux-aarch64-${{ env.BRANCH_NAME }}
+      - name: Save ccache
+        if: always()
+        uses: tespkg/actions-cache/save@v1
+        with:
+          endpoint: hel1.your-objectstorage.com
+          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
+          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
+          bucket: gha-cache
+          path: /home/runner/.cache/ccache
+          key: ccache-release-linux-aarch64-${{ env.BRANCH_NAME }}
       
-  #     - name: Run clang-tidy
-  #       run: scripts/clang-tidy-only-diff.sh $(nproc)
+      - name: Run clang-tidy
+        run: scripts/clang-tidy-only-diff.sh $(nproc)
 
-  #     # TODO: utrecht_tiles fails compilation with "illegal instruction"
-  #     - name: Run gurka tests
-  #       run: make -C build -j$(nproc) run-gurka
+      # TODO: utrecht_tiles fails compilation with "illegal instruction"
+      - name: Run gurka tests
+        run: make -C build -j$(nproc) run-gurka
       
-  #     - name: Install Valhalla
-  #       run: sudo make -C build install
+      - name: Install Valhalla
+        run: sudo make -C build install
       
-  #     - name: Setup tmate session
-  #       uses: mxschmitt/action-tmate@v3
-  #       if: ${{ env.SETUP_TMATE == 'true' || failure() }}
-  #       with:
-  #         detached: true
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
+        with:
+          detached: true
