wrong build dir

diff --git a/.github/workflows/osx_win_python_builds.yml b/.github/workflows/osx_win_python_builds.yml
--- a/.github/workflows/osx_win_python_builds.yml
+++ b/.github/workflows/osx_win_python_builds.yml
@@ -37,68 +37,68 @@ on:
         default: false
 
 jobs:
-  build_python_wheels_linux:
-    name: Build Linux Python wheels
-    runs-on: ubuntu-latest
-    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-          # we need to fetch all tags for setuptools-scm to work properly
-          fetch-depth: 0
-          fetch-tags: true
+  # build_python_wheels_linux:
+  #   name: Build Linux Python wheels
+  #   runs-on: ubuntu-latest
+  #   if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #         # we need to fetch all tags for setuptools-scm to work properly
+  #         fetch-depth: 0
+  #         fetch-tags: true
 
-      # this is only used to run cibuildwheel
-      - name: Configure Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.12'
+  #     # this is only used to run cibuildwheel
+  #     - name: Configure Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.12'
 
-      - name: Get branch name
-        run: echo "VALHALLA_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
+  #     - name: Get branch name
+  #       run: echo "VALHALLA_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
 
-      - name: Determine package to publish
-        run: |
-          VALHALLA_RELEASE_PKG="pyvalhalla"
-          if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
-            VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
-          fi
-          echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
+  #     - name: Determine package to publish
+  #       run: |
+  #         VALHALLA_RELEASE_PKG="pyvalhalla"
+  #         if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
+  #           VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
+  #         fi
+  #         echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
 
-      - name: Restore cache
-        id: cache-ccache-restore
-        uses: actions/cache/restore@v4
-        with:
-          path: /project/.cache/ccache
-          key: ccache-manylinux_2_28_x86_64
+  #     - name: Restore cache
+  #       id: cache-ccache-restore
+  #       uses: actions/cache/restore@v4
+  #       with:
+  #         path: /project/.cache/ccache
+  #         key: ccache-manylinux_2_28_x86_64
 
-      - uses: pypa/cibuildwheel@v2.23.3
-        env:
-          # /host is mounted from the host system to the manylinux container
-          CIBW_ENVIRONMENT: >
-            CCACHE_DIR=/host/project/.cache/ccache
-            VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
+  #     - uses: pypa/cibuildwheel@v2.23.3
+  #       env:
+  #         # /host is mounted from the host system to the manylinux container
+  #         CIBW_ENVIRONMENT: >
+  #           CCACHE_DIR=/host/project/.cache/ccache
+  #           VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
 
-      - name: Delete cache to save the latest
-        run: |
-          KEY="${{ steps.cache-ccache-restore.outputs.cache-primary-key }}"
-          gh cache delete ${KEY} || true
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Delete cache to save the latest
+  #       run: |
+  #         KEY="${{ steps.cache-ccache-restore.outputs.cache-primary-key }}"
+  #         gh cache delete ${KEY} || true
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Save cache
-        if: always()
-        uses: actions/cache/save@v4
-        with:
-          path: /project/.cache/ccache
-          key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}
+  #     - name: Save cache
+  #       if: always()
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: /project/.cache/ccache
+  #         key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}
 
-      - name: Upload wheels
-        uses: actions/upload-artifact@v4
-        with:
-          name: wheels-linux-x64
-          path: wheelhouse/*.whl
+  #     - name: Upload wheels
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: wheels-linux-x64
+  #         path: wheelhouse/*.whl
   
   build_osx:
     runs-on: macos-14
@@ -193,178 +193,179 @@ jobs:
           detached: true
           timeout-minutes: 15
   
-  build_win:
-    name: Build Win & Python wheels
-    runs-on: windows-2022
-    env:
-      BUILD_TYPE: Release
-      MSVC_VERSION: "2022"
-      VCPKG_VERSION: "5e5d0e1"
-      VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions
-      VCPKG_DISABLE_COMPILER_TRACKING: ON
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-          # we need to fetch all tags for setuptools-scm to work properly
-          fetch-depth: 0
-          fetch-tags: true
+  # build_win:
+  #   name: Build Win & Python wheels
+  #   runs-on: windows-2022
+  #   env:
+  #     BUILD_TYPE: Release
+  #     MSVC_VERSION: "2022"
+  #     VCPKG_VERSION: "5e5d0e1"
+  #     VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions
+  #     VCPKG_DISABLE_COMPILER_TRACKING: ON
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #         # we need to fetch all tags for setuptools-scm to work properly
+  #         fetch-depth: 0
+  #         fetch-tags: true
 
-      # we add a custom triplet to avoid cache misses as much as possible
-      # https://github.com/microsoft/vcpkg/issues/26346#issuecomment-1319244766
-      - name: Configure vckpg
-        shell: bash
-        run: |
-          echo "VCPKG_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
-          echo "VCPKG_OVERLAY_TRIPLETS=${{ github.workspace }}/vcpkg/custom-triplets" >> $GITHUB_ENV
-          echo "VCPKG_DEFAULT_TRIPLET=custom-x64-windows" >> $GITHUB_ENV
-          echo "VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg/archives" >> $GITHUB_ENV
+  #     # we add a custom triplet to avoid cache misses as much as possible
+  #     # https://github.com/microsoft/vcpkg/issues/26346#issuecomment-1319244766
+  #     - name: Configure vckpg
+  #       shell: bash
+  #       run: |
+  #         echo "VCPKG_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
+  #         echo "VCPKG_OVERLAY_TRIPLETS=${{ github.workspace }}/vcpkg/custom-triplets" >> $GITHUB_ENV
+  #         echo "VCPKG_DEFAULT_TRIPLET=custom-x64-windows" >> $GITHUB_ENV
+  #         echo "VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg/archives" >> $GITHUB_ENV
 
-      - name: Install GNU make & awk
-        run: choco install gawk make
+  #     - name: Install GNU make & awk
+  #       run: choco install gawk make
 
-      - name: Install vcpkg
-        shell: bash
-        run: |
-          git clone https://github.com/microsoft/vcpkg.git
-          cd vcpkg
-          git checkout $VCPKG_VERSION
-          mkdir archives
-          mkdir "$VCPKG_OVERLAY_TRIPLETS"
-          TRIPLET_FILE="$VCPKG_OVERLAY_TRIPLETS/$VCPKG_DEFAULT_TRIPLET.cmake"
-          cp triplets/x64-windows.cmake "$TRIPLET_FILE"
-          echo "set(VCPKG_BUILD_TYPE release)" >> "$TRIPLET_FILE"
-          echo "set(VCPKG_DISABLE_COMPILER_TRACKING $VCPKG_DISABLE_COMPILER_TRACKING)" >> "$TRIPLET_FILE"
-          cmd.exe /c bootstrap-vcpkg.bat
+  #     - name: Install vcpkg
+  #       shell: bash
+  #       run: |
+  #         git clone https://github.com/microsoft/vcpkg.git
+  #         cd vcpkg
+  #         git checkout $VCPKG_VERSION
+  #         mkdir archives
+  #         mkdir "$VCPKG_OVERLAY_TRIPLETS"
+  #         TRIPLET_FILE="$VCPKG_OVERLAY_TRIPLETS/$VCPKG_DEFAULT_TRIPLET.cmake"
+  #         cp triplets/x64-windows.cmake "$TRIPLET_FILE"
+  #         echo "set(VCPKG_BUILD_TYPE release)" >> "$TRIPLET_FILE"
+  #         echo "set(VCPKG_DISABLE_COMPILER_TRACKING $VCPKG_DISABLE_COMPILER_TRACKING)" >> "$TRIPLET_FILE"
+  #         cmd.exe /c bootstrap-vcpkg.bat
 
-      # make sure we save vcpkg packages even if build fails
-      # note, we don't use vcpkg "command line" mode, but "cmake manifest" mode
-      - name: Restore vcpkg packages
-        id: vcpkg-restore
-        uses: actions/cache/restore@v3
-        with:
-          key: vcpkg=${{ env.VCPKG_VERSION }}-msvc=${{ env.MSVC_VERSION }}-json=${{ hashFiles('vcpkg.json') }}
-          path: |
-            vcpkg/*
-            !vcpkg/downloads
-            !vcpkg/docs
-            !vcpkg/buildtrees
-            vcpkg/downloads/tools
+  #     # make sure we save vcpkg packages even if build fails
+  #     # note, we don't use vcpkg "command line" mode, but "cmake manifest" mode
+  #     - name: Restore vcpkg packages
+  #       id: vcpkg-restore
+  #       uses: actions/cache/restore@v3
+  #       with:
+  #         key: vcpkg=${{ env.VCPKG_VERSION }}-msvc=${{ env.MSVC_VERSION }}-json=${{ hashFiles('vcpkg.json') }}
+  #         path: |
+  #           vcpkg/*
+  #           !vcpkg/downloads
+  #           !vcpkg/docs
+  #           !vcpkg/buildtrees
+  #           vcpkg/downloads/tools
 
-      - name: Setup Developer Command Prompt for VS
-        uses: ilammy/msvc-dev-cmd@v1
+  #     - name: Setup Developer Command Prompt for VS
+  #       uses: ilammy/msvc-dev-cmd@v1
 
-      - name: Configure CMake
-        shell: bash
-        run: |
-          cmake --version
-          cmake -B build \
-            -G "Visual Studio 17 2022" \
-            -A x64 \
-            -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
-            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_TOOLCHAIN_FILE" \
-            -DVCPKG_OVERLAY_TRIPLETS="$VCPKG_OVERLAY_TRIPLETS" \
-            -DVCPKG_TARGET_TRIPLET="$VCPKG_DEFAULT_TRIPLET" \
-            -DVCPKG_INSTALL_OPTIONS="$VCPKG_INSTALL_OPTIONS" \
-            -DENABLE_DATA_TOOLS=ON \
-            -DENABLE_TOOLS=ON \
-            -DENABLE_PYTHON_BINDINGS=OFF \
-            -DENABLE_HTTP=ON \
-            -DENABLE_TESTS=OFF \
-            -DENABLE_CCACHE=OFF \
-            -DENABLE_SERVICES=OFF \
-            -DPREFER_EXTERNAL_DEPS=ON \
-            -DENABLE_GDAL=ON
+  #     - name: Configure CMake
+  #       shell: bash
+  #       run: |
+  #         cmake --version
+  #         cmake -B build \
+  #           -G "Visual Studio 17 2022" \
+  #           -A x64 \
+  #           -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
+  #           -DCMAKE_TOOLCHAIN_FILE="$VCPKG_TOOLCHAIN_FILE" \
+  #           -DVCPKG_OVERLAY_TRIPLETS="$VCPKG_OVERLAY_TRIPLETS" \
+  #           -DVCPKG_TARGET_TRIPLET="$VCPKG_DEFAULT_TRIPLET" \
+  #           -DVCPKG_INSTALL_OPTIONS="$VCPKG_INSTALL_OPTIONS" \
+  #           -DENABLE_DATA_TOOLS=ON \
+  #           -DENABLE_TOOLS=ON \
+  #           -DENABLE_PYTHON_BINDINGS=OFF \
+  #           -DENABLE_HTTP=ON \
+  #           -DENABLE_TESTS=OFF \
+  #           -DENABLE_CCACHE=OFF \
+  #           -DENABLE_SERVICES=OFF \
+  #           -DPREFER_EXTERNAL_DEPS=ON \
+  #           -DENABLE_GDAL=ON
 
-      - name: Save vcpkg packages (always, to avoid redundant rebuilds)
-        uses: actions/cache/save@v3
-        with:
-          key: ${{ steps.vcpkg-restore.outputs.cache-primary-key }}
-          path: |
-            vcpkg/*
-            !vcpkg/downloads
-            !vcpkg/docs
-            !vcpkg/buildtrees
-            vcpkg/downloads/tools
+  #     - name: Save vcpkg packages (always, to avoid redundant rebuilds)
+  #       uses: actions/cache/save@v3
+  #       with:
+  #         key: ${{ steps.vcpkg-restore.outputs.cache-primary-key }}
+  #         path: |
+  #           vcpkg/*
+  #           !vcpkg/downloads
+  #           !vcpkg/docs
+  #           !vcpkg/buildtrees
+  #           vcpkg/downloads/tools
 
-      - name: Build Valhalla
-        run: |
-          cmake --build build --config Release -- /clp:ErrorsOnly /p:BuildInParallel=true /m:4
-          cmake --build build --config Release --target install
+  #     - name: Build Valhalla
+  #       run: |
+  #         cmake --build build --config Release -- /clp:ErrorsOnly /p:BuildInParallel=true /m:4
+  #         cmake --build build --config Release --target install
 
-      - name: Test Executable
-        shell: bash
-        run: |
-          set PATH=$PATH:${{ github.workspace }}/build/vcpkg_installed/$BUILD_TYPE/bin
-          ./build/$BUILD_TYPE/valhalla_build_tiles.exe -c ./test/win/valhalla.json ./test/data/utrecht_netherlands.osm.pbf
-          ./build/$BUILD_TYPE/valhalla_run_isochrone.exe --config ./test/win/valhalla.json -j "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
-          ./build/$BUILD_TYPE/valhalla_service.exe ./test/win/valhalla.json isochrone "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
+  #     - name: Test Executable
+  #       shell: bash
+  #       run: |
+  #         set PATH=$PATH:${{ github.workspace }}/build/vcpkg_installed/$BUILD_TYPE/bin
+  #         ./build/$BUILD_TYPE/valhalla_build_tiles.exe -c ./test/win/valhalla.json ./test/data/utrecht_netherlands.osm.pbf
+  #         ./build/$BUILD_TYPE/valhalla_run_isochrone.exe --config ./test/win/valhalla.json -j "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
+  #         ./build/$BUILD_TYPE/valhalla_service.exe ./test/win/valhalla.json isochrone "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
       
-      - name: Determine package to publish
-        if: github.event_name != 'pull_request' && ${{ github.repository_owner == 'valhalla' }}
-        shell: bash
-        run: |
-          VALHALLA_RELEASE_PKG="pyvalhalla"
-          if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
-            VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
-          fi
-          echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
+  #     - name: Determine package to publish
+  #       if: github.event_name != 'pull_request' && ${{ github.repository_owner == 'valhalla' }}
+  #       shell: bash
+  #       run: |
+  #         VALHALLA_RELEASE_PKG="pyvalhalla"
+  #         if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
+  #           VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
+  #         fi
+  #         echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
         
-      - name: Print libs
-        shell: bash
-        run: |
-          ls -l build/vcpkg_installed/custom-x64-windows/lib
-          ls -l build/vcpkg_installed/custom-x64-windows/bin
+  #     - name: Print libs
+  #       shell: bash
+  #       run: |
+  #         ls -l build/vcpkg_installed/custom-x64-windows/lib
+  #         ls -l build/vcpkg_installed/custom-x64-windows/bin
       
-      - uses: pypa/cibuildwheel@v2.23.3
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
-        env:
-          # used in setup.py
-          CIBW_ENVIRONMENT: >
-            VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
-          CIBW_ENVIRONMENT_WINDOWS: >
-            VCPKG_ARCH_ROOT=build/vcpkg_installed/custom-x64-windows
-          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
-            delvewheel repair --add-path build/vcpkg_installed/custom-x64-windows/bin {wheel} -w {dest_dir}
+  #     - uses: pypa/cibuildwheel@v2.23.3
+  #       if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+  #       env:
+  #         # used in setup.py
+  #         CIBW_ENVIRONMENT: >
+  #           VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
+  #         CIBW_ENVIRONMENT_WINDOWS: >
+  #           VCPKG_ARCH_ROOT=build/vcpkg_installed/custom-x64-windows
+  #         CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
+  #           delvewheel repair --add-path build/vcpkg_installed/custom-x64-windows/bin {wheel} -w {dest_dir}
 
-      - name: Upload wheels
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: wheels-win-amd64
-          path: wheelhouse/*.whl
+  #     - name: Upload wheels
+  #       if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: wheels-win-amd64
+  #         path: wheelhouse/*.whl
 
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
-        # only run this if manually invoked or a previous job failed
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
-        with:
-          detached: true
+  #     - name: Setup tmate session
+  #       uses: mxschmitt/action-tmate@v3
+  #       # only run this if manually invoked or a previous job failed
+  #       if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+  #       with:
+  #         detached: true
 
-  verify_wheels:
-    name: Verify wheels with executables in a fresh environment
-    needs: [build_python_wheels_linux]
-    runs-on: ubuntu-latest
-    container: python:3.13-slim-bookworm
-    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
-    steps:
-      - uses: actions/checkout@v4
+  # verify_wheels:
+  #   name: Verify wheels with executables in a fresh environment
+  #   needs: [build_python_wheels_linux]
+  #   runs-on: ubuntu-latest
+  #   container: python:3.13-slim-bookworm
+  #   if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: actions/download-artifact@v4
-        with:
-          path: dist
-          merge-multiple: true
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         path: dist
+  #         merge-multiple: true
       
-      - name: Run test
-        run: |
-          apt-get update -y
-          apt-get install -y file
-          python -m pip install dist/*cp313-manylinux*.whl
-          ./src/bindings/python/test/test_pyvalhalla_package.sh
+  #     - name: Run test
+  #       run: |
+  #         apt-get update -y
+  #         apt-get install -y file
+  #         python -m pip install dist/*cp313-manylinux*.whl
+  #         ./src/bindings/python/test/test_pyvalhalla_package.sh
   
   upload_all:
     name: Upload if release
-    needs: [verify_wheels, build_osx, build_win]
+    # needs: [verify_wheels, build_osx, build_win]
+    needs: [build_osx]
     runs-on: ubuntu-latest
     # if: ${{ always() }}
     if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
