change pyvalhalla-git releases to once a week instead of every master commit; clean up some in the yml

diff --git a/.github/workflows/osx_win_python_builds.yml b/.github/workflows/osx_win_python_builds.yml
--- a/.github/workflows/osx_win_python_builds.yml
+++ b/.github/workflows/osx_win_python_builds.yml
@@ -7,6 +7,10 @@ name: Build OSX, Win & Python bindings
 #   - https://pypi.org/project/pyvalhalla-git/ for master pushes
 
 on:
+  # We run this once a week so we regularly publish pyvalhalla-git
+  # but not on _every_ master commit
+  schedule:
+    - cron: "0 0 * * 0"
   push:
     paths-ignore:
       - "*.md"
@@ -35,11 +39,17 @@ on:
         required: false
         default: false
 
+env:
+  # only run tmate if manually invoked and debug_enabled == true or a previous step failed
+  SETUP_TMATE: ${{ (((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) || failure()) && (github.repository_owner == 'valhalla') }}
+  # only publish to PyPI on tags, schedule or workflow_dispatch (only on master!)
+  PUBLISH_PYPI: ${{ (startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') || ((github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master'))) && (github.repository_owner == 'valhalla') }}
+
 jobs:
   build_python_wheels_linux:
     name: Build Linux Python wheels
     runs-on: ubuntu-latest
-    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+    if: ${{ env.PUBLISH_PYPI }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -74,7 +84,7 @@ jobs:
 
       - uses: pypa/cibuildwheel@v2.23.3
         env:
-          # /host is mounted from the host system to the manylinux container
+          # the host system's "/" is mounted to "/host" in the manylinux container
           CIBW_ENVIRONMENT: >
             CCACHE_DIR=/host/project/.cache/ccache
             VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
@@ -101,8 +111,7 @@ jobs:
 
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
-        # only run this if manually invoked and debug_enabled == true or a previous step failed
-        if: ${{ (((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) || failure()) && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.SETUP_TMATE }}
         with:
           detached: true
   
@@ -169,23 +178,23 @@ jobs:
       # only package python bindings if it's not a PR
 
       - name: Determine package to publish
-        if: github.event_name != 'pull_request' && ${{ github.repository_owner == 'valhalla' }}
+        if: ${{ env.PUBLISH_PYPI }}
         run: |
           VALHALLA_RELEASE_PKG="pyvalhalla"
-          if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
+          if [[ ${{ startsWith(github.ref, 'refs/tags') }} == "false" ]]; then
             VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
           fi
           echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
       
       - uses: pypa/cibuildwheel@v2.23.3
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.PUBLISH_PYPI }}
         env:
           CIBW_ENVIRONMENT: >
             VALHALLA_RELEASE_PKG=${{ env.VALHALLA_RELEASE_PKG }}
           MACOSX_DEPLOYMENT_TARGET: 14
 
       - name: Upload wheels
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.PUBLISH_PYPI }}
         uses: actions/upload-artifact@v4
         with:
           name: wheels-osx-arm64
@@ -194,7 +203,7 @@ jobs:
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
         # only run this if manually invoked and debug_enabled == true or a previous step failed
-        if: ${{ (((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) || failure()) && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.SETUP_TMATE }}
         with:
           detached: true
   
@@ -306,11 +315,11 @@ jobs:
           ./build/$BUILD_TYPE/valhalla_service.exe ./test/win/valhalla.json isochrone "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
       
       - name: Determine package to publish
-        if: github.event_name != 'pull_request' && ${{ github.repository_owner == 'valhalla' }}
+        if: ${{ env.PUBLISH_PYPI }}
         shell: bash
         run: |
           VALHALLA_RELEASE_PKG="pyvalhalla"
-          if [[ "${GITHUB_REF#refs/heads/}" != "refs/tags*" ]]; then
+          if [[ ${{ startsWith(github.ref, 'refs/tags') }} == "false" ]]; then
             VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
           fi
           echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
@@ -322,7 +331,7 @@ jobs:
           ls -l build/vcpkg_installed/custom-x64-windows/bin
       
       - uses: pypa/cibuildwheel@v2.23.3
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.PUBLISH_PYPI }}
         env:
           # used in setup.py
           CIBW_ENVIRONMENT: >
@@ -333,7 +342,7 @@ jobs:
             delvewheel repair --add-path build/vcpkg_installed/custom-x64-windows/bin {wheel} -w {dest_dir}
 
       - name: Upload wheels
-        if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.PUBLISH_PYPI }}
         uses: actions/upload-artifact@v4
         with:
           name: wheels-win-amd64
@@ -342,7 +351,7 @@ jobs:
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
         # only run this if manually invoked and debug_enabled == true or a previous step failed
-        if: ${{ (((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) || failure()) && (github.repository_owner == 'valhalla') }}
+        if: ${{ env.SETUP_TMATE }}
         with:
           detached: true
 
@@ -351,7 +360,7 @@ jobs:
     needs: [build_python_wheels_linux]
     runs-on: ubuntu-latest
     container: python:3.13-slim-bookworm
-    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+    if: ${{ env.PUBLISH_PYPI }}
     steps:
       - uses: actions/checkout@v4
 
@@ -372,7 +381,7 @@ jobs:
     needs: [verify_wheels, build_osx, build_win]
     runs-on: ubuntu-latest
     # if: ${{ always() }}
-    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'valhalla') }}
+    if: ${{ env.PUBLISH_PYPI }}
 
     permissions:
       id-token: write # This is required for requesting the JWT from Github for PyPI
